### ISSUE TITLE
any suggestions for improvement

### ISSUE THREAD

**Issue by DILIU1** [dongyangli-del/EEG_Image_decode#10]
I attempted to generate all images for parts of subject 1 and 8. Unfortunately, the results did not align with those presented in your paper, and the quality was less than satisfactory. Could you kindly offer any suggestions for improvement?
![output](https://github.com/dongyangli-del/EEG_Image_decode/assets/30624563/fa0a3973-ad4b-483c-805f-f5ac88df70ff)
![output](https://github.com/dongyangli-del/EEG_Image_decode/assets/30624563/f79b6be1-254d-4c81-a989-a25a8faf6a71)

**Comment by dongyangli-del** [comment]
@DILIU1 Now you need to ensure the following checks:
Use Img features to perform retrieval tasks and save the model
Load the correct model and map_location to the correct cuda device
Ensure that the clip feature extraction is not normalized, and the retrieval task training process is not normalized. Ensure that the std of the overall eeg features and img features is in a reasonable state.

**Comment by DILIU1** [comment]
> @DILIU1 Now you need to ensure the following checks: Use Img features to perform retrieval tasks and save the model Load the correct model and map_location to the correct cuda device Ensure that the clip feature extraction is not normalized, and the retrieval task training process is not normalized. Ensure that the std of the overall eeg features and img features is in a reasonable state.

Thank you for your suggestions. I have run the code according to your instructions. Are you suggesting that I might have overlooked a crucial part, or should I review the entire process on my own?

**Comment by dongyangli-del** [comment]
@DILIU1  Hi, you can check the correctness of the generated eeg_features and the correctness of the img embedding generated by priority_diffusion.

You can also refer to other people's correct practices in issues that have been closed in the past.

**Comment by generic111** [comment]
@DILIU1 I am facing the same issue as you. How did you go about fixing it?
