### ISSUE TITLE
 If I wish to train my own image data, how can I obtain a new model like ViT-H-14_features_test.pt and ViT-H-14_features_train.pt?

### ISSUE THREAD

**Issue by DILIU1** [dongyangli-del/EEG_Image_decode#11]

**Comment by dongyangli-del** [comment]
@DILIU1 Actually, extracting features is automatic. Their implementation can be found [eegdatasets_leaveone.py](https://github.com/dongyangli-del/EEG_Image_decode/blob/main/Retrieval/eegdatasets_leaveone.py). And you just need to run normally and declare the image path, if no pt file is detected, it will automatically extract image and text features.

**Comment by DILIU1** [comment]
> @DILIU1 Actually, extracting features is automatic. Their implementation can be found [eegdatasets_leaveone.py](https://github.com/dongyangli-del/EEG_Image_decode/blob/main/Retrieval/eegdatasets_leaveone.py). And you just need to run normally and declare the image path, if no pt file is detected, it will automatically extract image and text features.
I ran two tests, and only when using your uploaded ViT-H-14_features_test.pt did I get relatively good results. When I use the ViT-H-14_features_test.pt that I generated myself, the final results are very poor. Do you know what might be causing this?

**Comment by DILIU1** [comment]
> @DILIU1 Actually, extracting features is automatic. Their implementation can be found [eegdatasets_leaveone.py](https://github.com/dongyangli-del/EEG_Image_decode/blob/main/Retrieval/eegdatasets_leaveone.py). And you just need to run normally and declare the image path, if no pt file is detected, it will automatically extract image and text features.

I ran two tests, and only when using your uploaded ViT-H-14_features_test.pt did I get relatively good results. When I use the ViT-H-14_features_test.pt that I generated myself, the final results are very poor. Do you know what might be causing this?

**Comment by DILIU1** [comment]
> @DILIU1 This may be because there is something wrong with your data. Check your pre-processing process and data correctness first, and then check the performance of the retrieval task.
> 
> After confirming the above process, the image generation is carried out.
I used the data you uploaded, and I can also get normal results using the image features you uploaded. Could there be a problem with the image feature extraction?

**Comment by DILIU1** [comment]
@dongyangli-del I used the data you uploaded, and I can also get normal results using the image features you uploaded. Could there be a problem with the image feature extraction?

**Comment by dongyangli-del** [comment]
@DILIU1 Is the performance of your model on the retrieval task normal? I think the features you extracted might be saved or loaded incorrectly.

**Comment by ArashAkbarinia** [comment]
Thank you @dongyangli-del for releasing the code of your model. I found it quite useful :).

Am I understanding correctly that you're using the exact test images of EEG for your retrieval test set?
In NICE they have excluded the exact images used in the EEG experiment, and for retrieval, they're using the average of all other images (from each concept).

If I do a similar procedure with your framework, the accuracy (top1) drops by 7% or so.

**Comment by dongyangli-del** [comment]
@ArashAkbarinia Hi, your idea is correct. 
In our work, we totally define three tasks (retrieval, classification and reconstruction). In retrieval and classification tasks, we always use test images as the test set, because this is more in line with the online decoding task scenario.

Of course, the use of additional images instead of stimulus images as templates in the NICE ([https://arxiv.org/abs/2308.13234](https://arxiv.org/abs/2308.13234)) article can also reflect the model performance to a certain extent:
"Before the test process, we use a few images that belong to the image concepts (classes) to be classified, and have not appeared in the EEG collection experiments. These images are processed and averaged to obtain one template for each concept."

So this mainly depends on your mission scenario.
