### ISSUE TITLE
test dataset

### ISSUE THREAD

**Issue by xuchengjian632** [dongyangli-del/EEG_Image_decode#13]
May I ask why in def __getitem__() index_n_sub_test has to be multiplied by 80 and test_index has to be divided by 80 when you have already averaged 80 repetitions of the test data in EEG_dataset() in EEG_Image_decode/Generation/eegdatasets_leaveone.py. 
![1](https://github.com/dongyangli-del/EEG_Image_decode/assets/63955818/f107e10d-6a4e-4742-b312-654a589896eb)
![2](https://github.com/dongyangli-del/EEG_Image_decode/assets/63955818/0fd129c4-4c60-495c-a9e4-676dc50fa3e2)

**Comment by dongyangli-del** [comment]
This is an engineering detail. We need to average the EEG data here, but the EEG labels still need to be correct. This is written to ensure that the corresponding label is found every time and can better match the data with the label.

**Comment by xuchengjian632** [comment]
> @xuchengjian632 This is an engineering detail. We need to average the EEG data here, but the EEG labels still need to be correct. This is written to ensure that the corresponding label is found every time and can better match the data with the label.

But here after data processing data_list and label_list are spliced with data dimensions of (200, 63, 250) and (200, ) respectively, don't the EEG data and labels already correspond to each other?
![0](https://github.com/dongyangli-del/EEG_Image_decode/assets/63955818/6ad18320-aca6-49b5-a6d0-5b2150585d51)

**Comment by xuchengjian632** [comment]
> @xuchengjian632 This is an engineering detail. We need to average the EEG data here, but the EEG labels still need to be correct. This is written to ensure that the corresponding label is found every time and can better match the data with the label.

But here after data processing data_list and label_list after cating the data dimensions are (200, 63, 250) and (200, ) respectively, the EEG data and labels don't already correspond to each other?
![0](https://github.com/dongyangli-del/EEG_Image_decode/assets/63955818/44802e67-41a8-45ef-86e2-261d38c23612)

**Comment by dongyangli-del** [comment]
@xuchengjian632 Obviously, (200, 63, 250) represents 200 categories, each category has 1 sample, and this dimension is omitted; each sample has 63 channels, and the length of each sample is 250;
(200, ) represents 200 categories, each category has 1 sample label, so this dimension is also omitted.

**Comment by xuchengjian632** [comment]
@dongyangli-del I understand the meaning of data dimensionality. What I mean is that, with the test dataset obtained, after being processed by the load_data() function, the EEG data and labels have already been matched (both the data and labels have the first dimension value of 200). So, is it necessary to divide by 80 again in the __getitem__(self, index)?

**Comment by dongyangli-del** [comment]
@xuchengjian632 Thank you for your question.
In our code, we considered a more general situation, because it is possible that the best results cannot be obtained by averaging the repetitions of all test sets.
According to the conclusions in the paper by song et al., the best results can be achieved on average at 55 repetitions. Our code provides scalability for this scaling low test.

![image](https://github.com/dongyangli-del/EEG_Image_decode/assets/62006079/9a35d6f9-f0a0-40c2-a7de-424862af820c)

**Comment by xuchengjian632** [comment]
@dongyangli-del So, does the code for obtaining data here not need to divide by 80 when normally acquiring test set data?

**Comment by dongyangli-del** [comment]
Hi @xuchengjian632 I think you didn't figure out the basic logic of the code. If you have other questions, you can add my wechat:KeepRevere2Nature.
Now that the original version of this issue has been resolved, I will close this issue.

**Comment by xuchengjian632** [comment]
@dongyangli-del Okay, thank you for your response.
