### ISSUE TITLE
huggingface Network address error

### ISSUE THREAD

**Issue by koro-github** [dongyangli-del/EEG_Image_decode#15]
when I was running ATM_S_reconstruction_scale_0_1000.py, an error occurred in the eegdatasets_leaveone.py file. I checked the cause online and said that the address of huggingface was incorrect.
![c11fc7b85a902e7d518ee40660677f2](https://github.com/dongyangli-del/EEG_Image_decode/assets/65952413/00dae7c7-8f86-40f1-a0ca-b979ba796e55)

**Comment by dongyangli-del** [comment]
Hi, @koro-github , If you are in mainland China, you need to set up a proxy based on your VPN. This means you need to fill in an IP address and port number with a foreign proxy:
```
proxy ='http://xx.xx.xx.xx:port'
os.environ['http_proxy']= proxy
os.environ['https_proxy']= proxy
```
But if you are in other regions outside of mainland China, these lines of code are unnecessary.

**Comment by koro-github** [comment]
Hi Dongyang, I have successfully run ATM_S_reconstruction_scale_0_1000.py and saved the weights. Now I am trying to run your Generation_metrics_sub1.ipynb, but there are some problems, some packages are not imported, can you tell me how to import them? Hi Dongyang, I have successfully run ATM_S_reconstruction_scale_0_1000.py and saved the weights. Now I am trying to run your Generation_metrics_sub1.ipynb, but there are some problems, some packages are not imported, can you tell me how to import them?
![40c57cbe8fba33365bb314a8df611ca](https://github.com/dongyangli-del/EEG_Image_decode/assets/65952413/cc450282-e10a-46d3-b4f3-d7bef4ba304f)

**Comment by koro-github** [comment]
Hi Dongyang, I have successfully run ATM_S_reconstruction_scale_0_1000.py and saved the weights. Now I am trying to run your Generation_metrics_sub1.ipynb, but there are some problems, some packages are not imported, can you tell me how to import them? Hi Dongyang, I have successfully run ATM_S_reconstruction_scale_0_1000.py and saved the weights. Now I am trying to run your Generation_metrics_sub1.ipynb, but there are some problems, some packages are not imported, can you tell me how to import them?
![94652617a685d929267d5556b19df6d](https://github.com/dongyangli-del/EEG_Image_decode/assets/65952413/f7027b74-c8ad-45ed-98ff-3235485e15a8)
![41786390a395be461d09c5240aeb846](https://github.com/dongyangli-del/EEG_Image_decode/assets/65952413/4c385b0b-a496-425f-95a5-03fef9feb4f2)

**Comment by koro-github** [comment]
Hi Dongyang, I have successfully run ATM_S_reconstruction_scale_0_1000.py and saved the weights. Now I am trying to run your Generation_metrics_sub1.ipynb, but there are some problems, some packages are not imported, can you tell me how to import them?
![94652617a685d929267d5556b19df6d](https://github.com/dongyangli-del/EEG_Image_decode/assets/65952413/d4e09f4e-2950-484e-be8e-4c666ee615cb)
![41786390a395be461d09c5240aeb846](https://github.com/dongyangli-del/EEG_Image_decode/assets/65952413/bbfd15d7-f189-4e4c-a8ea-50bed1b45371)

**Comment by dongyangli-del** [comment]
These classes or functions are defined in the `custom_pipeline.py` module. 
And if you need them, you should `uncomment` this code and import these modules:
![image](https://github.com/dongyangli-del/EEG_Image_decode/assets/62006079/7d894857-4a7c-488d-800a-8f98436ae0a5)

**Comment by koro-github** [comment]
Thanks for your answer. Now the problem of import package has been solved, but I still can't find the list of texts. 
1. Can you tell me how to find or define a list of texts? 2.Generation_metrics_sub1.ipynb file contains train prior diffusion. Could you please tell me the correct reading order of ipynb file?

**Comment by koro-github** [comment]
Thanks for your answer. Now the problem of import package has been solved, but I still can't find the list of texts.
1.Can you tell me how to find or define a list of texts? 
2.Generation_metrics_sub1.ipynb file contains train prior diffusion. Could you please tell me the correct reading order of ipynb file?
![3f22af9766c267da96e893a95aca20d](https://github.com/dongyangli-del/EEG_Image_decode/assets/65952413/4fbeb59b-40ee-46da-835d-da6b4a25051f)

**Comment by dongyangli-del** [comment]
1. I assume that the list of texts you mentioned refers to the text description of each image. Here, the image name label is simply used.
2. Generation_metrics_sub1.ipynb is missing the definition of texts, I have updated it. Other files are not missing, you can try using other files first.

**Comment by koro-github** [comment]
thanks you answer,dongyang.  I can't find the difference between ATM_S_insubject_retrieval.py and ATM_S_insubject_classification.py.  One of them is retrieval and the other is classification. What's the difference in the code.
  there  model 、acc_compute、dataset  are same. 
  ATM_S_insubject_classification.py
![4dffb4e6a25e332b44f10d189d2e44a](https://github.com/dongyangli-del/EEG_Image_decode/assets/65952413/6c4b948d-1ccf-4c85-958c-6fcabc099327)
![4dffb4e6a25e332b44f10d189d2e44a](https://github.com/dongyangli-del/EEG_Image_decode/assets/65952413/6c4b948d-1ccf-4c85-958c-6fcabc099327)
![4dffb4e6a25e332b44f10d189d2e44a](https://github.com/dongyangli-del/EEG_Image_decode/assets/65952413/6c4b948d-1ccf-4c85-958c-6fcabc099327)

  ATM_S_insubject_classification.py
![a26f4edf40dfdc87db5f2cbe9e79657](https://github.com/dongyangli-del/EEG_Image_decode/assets/65952413/5596d821-2362-497e-a6f8-3a8e5f57cdce)
![a26f4edf40dfdc87db5f2cbe9e79657](https://github.com/dongyangli-del/EEG_Image_decode/assets/65952413/5596d821-2362-497e-a6f8-3a8e5f57cdce)
![a26f4edf40dfdc87db5f2cbe9e79657](https://github.com/dongyangli-del/EEG_Image_decode/assets/65952413/5596d821-2362-497e-a6f8-3a8e5f57cdce)

**Comment by koro-github** [comment]
thanks you answer,dongyang.  I can't find the difference between ATM_S_insubject_retrieval.py and ATM_S_insubject_classification.py.  One of them is retrieval and the other is classification. What's the difference in the code.
  there  model 、acc_compute、dataset  are same. 
  ATM_S_insubject_classification.py
![4dffb4e6a25e332b44f10d189d2e44a](https://github.com/dongyangli-del/EEG_Image_decode/assets/65952413/6c4b948d-1ccf-4c85-958c-6fcabc099327)

  ATM_S_insubject_classification.py
![a26f4edf40dfdc87db5f2cbe9e79657](https://github.com/dongyangli-del/EEG_Image_decode/assets/65952413/5596d821-2362-497e-a6f8-3a8e5f57cdce)
