### ISSUE TITLE
Confusion about the test images path

### ISSUE THREAD

**Issue by generic111** [dongyangli-del/EEG_Image_decode#16]
In your data_config.json in the Generation folder, the "img_directory_test" points to "/home/ldy/Workspace/Generation/generated_imgs".

Does this mean that img_directory_test should point to the generated images by the model? 
Or does it just point to the folder with the test images?

**Comment by koro-github** [comment]
Just point to the folder of test images

**Comment by dongyangli-del** [comment]
Hi, @generic111, if you need to test the performance of image reconstruction, you need to set `img_directory_test `to `generated_imgs`, otherwise Just point to the folder of `test images`.

**Comment by koro-github** [comment]
thanks you answer,dongyang. I can't find the difference between ATM_S_insubject_retrieval.py and ATM_S_insubject_classification.py. One of them is retrieval and the other is classification. What's the difference in the code.
there model 、acc_compute、dataset are same.
ATM_S_insubject_classification.py
![4dffb4e6a25e332b44f10d189d2e44a](https://github.com/dongyangli-del/EEG_Image_decode/assets/65952413/af039e8a-d56a-4c9b-a024-79a427e6ab6e)

ATM_S_insubject_classification.py
![a26f4edf40dfdc87db5f2cbe9e79657](https://github.com/dongyangli-del/EEG_Image_decode/assets/65952413/4cacff65-1e9a-4666-bcd1-22686b13df72)

**Comment by dongyangli-del** [comment]
Hi, @koro-github , [our paper](https://arxiv.org/abs/2403.07721) clearly points out the difference between retrieval tasks and classification tasks, namely:
The `retrieval` task uses `image features` to calculate similarity during the test phase, while the `classification` task uses `text features` during the test phase. 
The representation alignment training process of the two is common, and `both use image features` to guide learning.

**Comment by koro-github** [comment]
Got it. Thank you

**Comment by generic111** [comment]
Hi @dongyangli-del, to confirm when training the model in ATM_S_reconstruction_scale_0_1000.py, I set the path of "img_directory_test" to the actual test images and when I want to test the performance of the model i set it to the generated images directory?

**Comment by dongyangli-del** [comment]
Hi, @generic111, yes. 
If you need to test the performance of image reconstruction, you need to set `img_directory_test `to `generated_imgs`, otherwise Just point to the folder of `test images`.
