### ISSUE TITLE
NameError: name 'DiffusionPriorUNet' is not defined

### ISSUE THREAD

**Issue by FreeStyleFreeLunch** [dongyangli-del/EEG_Image_decode#17]
Traceback (most recent call last):
  File "/home/loafei124/workspace/EEG_Image_decode/Generation/Generation_metrics_sub1.py", line 362, in <module>
    diffusion_prior = DiffusionPriorUNet(cond_dim=1024, dropout=0.1)
NameError: name 'DiffusionPriorUNet' is not defined

**Comment by dongyangli-del** [comment]
Hi, @FreeStyleFreeLunch, we were missing a block of code that imports `DiffusionPriorUNet `modules, and this has been fixed. Please use the latest code.
