### ISSUE TITLE
When I run the Retrieval.py, it always have some problems like IndexError: list index out of range

### ISSUE THREAD

**Issue by 1074524075** [dongyangli-del/EEG_Image_decode#33]

**Comment by OKWELLHELLO** [comment]
Hello, I also encountered the same problem while running train_vae_latent_512_low_level_no-average. py. How did you solve it.

![Image](https://github.com/user-attachments/assets/5f57a152-813a-4feb-9483-e2adbdea734b)

**Comment by 1074524075** [comment]
> Hello, I also encountered the same problem while running train_vae_latent_512_low_level_no-average. py. How did you solve it.
> 
> ![Image](https://github.com/user-attachments/assets/5f57a152-813a-4feb-9483-e2adbdea734b)

数据集有问题，少了几个分类导致的
