### ISSUE TITLE
Hardware specs when running the model

### ISSUE THREAD

**Issue by generic111** [dongyangli-del/EEG_Image_decode#4]
Hi @dongyangli-del ,

I'm encountering a Killed message when trying to run the pre-processing code.  This is probably due to a memory issue (too little RAM). Is there anyway around this? And could I get the specs of the machine you ran the code on?

**Comment by dongyangli-del** [comment]
@generic111 Hello, based on your question and other people's normal operation, I think the configuration of the machine is not the main factor. The possible reason is that the disk does not have enough space to store the preprocessed data.

If memory does become a problem for you in preprocessing, you can modify the code to only process the data of one subject at a time:
![image](https://github.com/dongyangli-del/EEG_Image_decode/assets/62006079/e2f4b4b4-7595-4298-aa78-7e0f3a12e870)


In addition, this is the server configuration I use. Obviously, I recommend using a server over a personal computer:

![image](https://github.com/dongyangli-del/EEG_Image_decode/assets/62006079/3e662f5e-6ee4-476f-ad94-edd4c6deaa14)

**Comment by generic111** [comment]
Thank you for this information. I have roughly 400GB on my disk. That should be enough for the pre-processed data which is roughly 100GB from what I can see on the BaiduNetDisk?

**Comment by dongyangli-del** [comment]
@generic111 Enough to revive the project. But if you want to experiment with MEG data or other preprocessing methods, I recommend leaving more room.
