### ISSUE TITLE
Where is eegencoder?

### ISSUE THREAD

**Issue by microcourier** [dongyangli-del/EEG_Image_decode#5]
When I followed the instructions in the readme to execute "python ATM_S_insubject_retrieval.py", the program reported an error:
`
Traceback (most recent call last):
  File "ATM_S_insubject_retrieval.py", line 21, in <module>
    from eegencoder import eeg_encoder
ModuleNotFoundError: No module named 'eegencoder'
`
I couldn't find the module 'eegencoder' in the code. How can I obtain it?

**Comment by dongyangli-del** [comment]
@microcourier Hi, thanks for pointing out a small problem in the code. In fact, this eegencoder module is an abandoned python module, and the real eegencoder has been defined in ATM_S_insubject_retrieval.py.

Please comment out the original line of " import eeg_encoder", or use the latest version of the code that I have updated.
