### ISSUE TITLE
Is it possible to upload the generated images for all subjects

### ISSUE THREAD

**Issue by generic111** [dongyangli-del/EEG_Image_decode#8]
Hi,

Is it possible for you to upload the generated images for all subjects to a google drive?

I am getting a lot of unrelated images for each category. The metrics generated from `Reconstruciton_Metric_ATM.ipynb` seems to be in line with what was mentioned in the paper.

I just ran `ATM_S_reconstruction_scale_0_1000.py` and `Generation_metric_sub1.ipynb` to get the images. Is there anything else I needed to do?

**Comment by dongyangli-del** [comment]
@generic111 
Of course, if you need it, I am willing to put the images generated for each subject into the Google driver's warehouse. _Generation_metric_sub1.ipynb_ can reconstruct the stimulus image corresponding to the corresponding subject for you. If you want to evaluate the generation quality, you can run _Reconstruciton_Metric_ATM.ipynb_ again.

But before that, as @bobwangPKU  pointed out, the training and testing methods used for retrieval and classification tasks have problems with implicit exposure bias. The generated code does not have this problem, and the current version of the code can be used as a reference . We will quickly update the latest version of the code to make the experimental results of retrieval and classification more credible.

We are steadfast in providing trustworthy code to interdisciplinary communities.

**Comment by dongyangli-del** [comment]
@generic111  Hi, the relevant code has been updated. Please clone the code repository again, which will make your results more rigorous. The relevant generated image collection has been uploaded [google driver](https://drive.google.com/drive/folders/1SAdAs73-w_N9ZVy2xAMsJZyyIE28Fnes?usp=sharing).
