### ISSUE TITLE
 When I run Generation_metrics_sub1.ipynb, I encountered the following error. Where should I go to get this file? Thank you.

### ISSUE THREAD

**Issue by DILIU1** [dongyangli-del/EEG_Image_decode#9]
<img width="1067" alt="企业微信截图_17134889529960" src="https://github.com/dongyangli-del/EEG_Image_decode/assets/30624563/834b3a89-e728-40a7-b381-99046d37a783">

**Comment by dongyangli-del** [comment]
Hi! If you run it for the first time, in _Generation_metrics_sub1.ipynb_, the corresponding eeg_features will be generated after running. Please replace the path with the eeg_features path you generated and continue running.

![image](https://github.com/dongyangli-del/EEG_Image_decode/assets/62006079/055e0beb-38cb-45a2-a304-de91f98f7a4e)

**Comment by DILIU1** [comment]
ok， i will try it! thx

**Comment by lwlBCI** [comment]
您好，我在运行ATM_S_insubject_retrieval.py文件时，似乎出现了torch.load问题，不知道是哪里出错了，如您看到，希望您能回复我一下，谢谢！
![image](https://github.com/dongyangli-del/EEG_Image_decode/assets/96649539/431b0be1-da64-4156-b809-64f48950c223)
![image](https://github.com/dongyangli-del/EEG_Image_decode/assets/96649539/78cd5691-eec2-4223-a039-5fc03eba0f12)

**Comment by dongyangli-del** [comment]
@lwlBCI This usually indicates a problem while trying to load a serialized file using torch.load. This may be because the file was not downloaded or saved correctly, or was corrupted during transfer.

Please delete the extracted feature files ViT-14_features_train.pt and ViT-14_features_test.pt and run again.

**Comment by DILIU1** [comment]
pip install transformers==0.27.0  Why can't I find this version of transforms?

**Comment by lwlBCI** [comment]
所以，可能是您提供的ViT-H-14_features_train.pt文件有问题吗？我在两台电脑上都下载并运行了您的项目，都遇到了相同的问题。当我尝试删除来重新生成此文件时，报错提示我的显存不够，所以我还是想使用您的ViT-H-14_features_train.pt文件。我已经给您主页的邮箱发送了邮件，如您不介意 希望您能加我一下，非常非常感谢，我真心想学习一下，感谢！

**Comment by lwlBCI** [comment]
ok，应该就是权重文件的问题，非常感谢！祝科研顺利！
